services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    buildCommand: docker build -t wordpress .
    envVars:
      - key: WORDPRESS_DB_HOST
        fromService: mysql
      - fromGroup: mysql

  - type: pserv
    name: mysql
    env: docker
    plan: free
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - fromGroup: mysql

envVarGroups:
  - name: mysql
    envVars:
      - key: MYSQL_DATABASE
        value: ilovecats
      - key: MYSQL_USER
        value: ailurotech
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true