services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    buildCommand: docker build -t wordpress .
    startCommand: docker run -p 8000:80 --env WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST --env WORDPRESS_DB_USER=$WORDPRESS_DB_USER --env WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD --env WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME wordpress
    envVars:
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wordpress-db
          property: database

  - type: web
    name: phpmyadmin
    env: docker
    image: phpmyadmin/phpmyadmin
    plan: free
    startCommand: docker run -p 8080:80 --env PMA_HOST=$PMA_HOST --env MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD phpmyadmin/phpmyadmin
    envVars:
      - key: PMA_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: MYSQL_ROOT_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password

databases:
  - name: wordpress-db
    type: mysql
    plan: free
    properties:
      mysqlVersion: 8.0
