services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    buildCommand: docker build -t wordpress .
    startCommand: docker run -p 8000:80 -v ./html:/var/www/html --env WORDPRESS_DB_HOST=db:3306 --env WORDPRESS_DB_USER=ailurotech --env WORDPRESS_DB_PASSWORD=ilovecats --env WORDPRESS_DB_NAME=ilovecats wordpress
    mounts:
      - path: /var/www/html
        volume: wordpress_html
    envVars:
      - key: WORDPRESS_DB_HOST
        value: db:3306
      - key: WORDPRESS_DB_USER
        value: ailurotech
      - key: WORDPRESS_DB_PASSWORD
        value: ilovecats
      - key: WORDPRESS_DB_NAME
        value: ilovecats

  - type: pserv
    name: db
    env: docker
    image: mariadb:latest
    plan: free
    startCommand: docker run -v db_data:/var/lib/mysql --env MARIADB_ROOT_PASSWORD=rootpassword --env MARIADB_DATABASE=ilovecats --env MARIADB_USER=ailurotech --env MARIADB_PASSWORD=ilovecats mariadb:latest --innodb_use_native_aio=0
    mounts:
      - path: /var/lib/mysql
        volume: db_data
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        value: rootpassword
      - key: MARIADB_DATABASE
        value: ilovecats
      - key: MARIADB_USER
        value: ailurotech
      - key: MARIADB_PASSWORD
        value: ilovecats

  - type: web
    name: phpmyadmin
    env: docker
    image: phpmyadmin/phpmyadmin
    plan: free
    startCommand: docker run -p 8080:80 --env PMA_HOST=db --env MYSQL_ROOT_PASSWORD=rootpassword phpmyadmin/phpmyadmin
    envVars:
      - key: PMA_HOST
        value: db
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword

volumes:
  - name: wordpress_html
  - name: db_data
